name: Publish to npm

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
