name: Publish to npm

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Configure npm auth
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "${NODE_AUTH_TOKEN}" ]; then
            echo "NPM_TOKEN is not set. Skipping publish.";
            exit 0;
          fi
          npm config set //registry.npmjs.org/:_authToken "${NODE_AUTH_TOKEN}"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build --if-present

      - name: Check package.json private
        id: check_private
        run: |
          if [ "$(cat package.json | jq -r '.private // false')" = "true" ]; then
            echo "Package is private; skipping publish.";
            echo "private=true" >> $GITHUB_OUTPUT;
            exit 0;
          fi
          echo "private=false" >> $GITHUB_OUTPUT;

      - name: Publish to npm
        if: steps.check_private.outputs.private == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # prefer pnpm publish when available; fallback to npm
          if command -v pnpm >/dev/null 2>&1; then
            pnpm publish --access public --no-git-checks
          else
            npm publish --access public
          fi
